Report when the TeX Live installation fails

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -39,6 +39,11 @@ else
     echo $VERSION > $TEXLIVE_CACHE/VERSION
 fi
 
+if [ ! `which pdflatex` ]; then
+    echo " !     TeX Live installation failed"
+    exit 1
+fi
+
 # Check for the existence of a suitable TeX document
 cd $BUILD_DIR
 if [ ! -f $DOCUMENT ]; then
